# Generated by Django 4.2 on 2023-04-15 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_alter_usertoken_token"),
    ]

    operations = [
        migrations.DeleteModel(name="UserToken",),
    ]
