name: Django CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: myimage
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: im@geb@ckend
        ports:
        - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dockerize
      run: |
        wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
        tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
        rm dockerize-linux-amd64-v0.6.1.tar.gz

    - name: Wait for postgres to start
      run: |
        dockerize -wait tcp://localhost:5432 -timeout 1m

    - name: Run database migrations
      run: |
        cd image_backend
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      run: |
        cd image_backend
        python manage.py test
