name: Django CI

on: [push, pull_request, workflow_dispatch]


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: myimage
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: im@geb@ckend
        ports:
        - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for postgres to start
      run: |
        dockerize -wait tcp://localhost:5432 -timeout 1m

    - name: Run database migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests
      run: |
        python manage.py test
